### ISSUE TITLE
Should send basename of the executable to NSM

### ISSUE THREAD

**Issue by Houston4444** [jean-emmanuel/loop192#2]
https://github.com/jean-emmanuel/loop192/blob/5ecaae690929b2f827fe4dc8cf067cfa521d4943/src/main.cpp#L239

loop192 should not send full path of the executable to the server, only basename. RaySession doesn't cares about it, except if program is launched from external, but new-session-manager may not be able to relaunch it.

> // Announce includes :dirty:capability because we're always clean

In this case, that would be nice to send a is_clean message ;)

**Comment by jean-emmanuel** [comment]
loop192 sends argv[0], which is what's recommended in the API. It's a full path only when the executable is called with a path (and it does make sense in this case to let nsm know where the executable is since it may not be in the PATH).

> In this case, that would be nice to send a is_clean message ;)

I disagree, there no reason to think a client is dirty when launched or right after opening the session specified by nsm.

**Comment by Houston4444** [comment]
> I disagree, there no reason to assume a client is dirty when launched or right after opening the session specified by nsm.

I don't understand. You say "we're always clean", use ":dirty:" and never send in the program `nsm_send_is_clean` or `nsm_send_is_dirty`. So, what is it for ?

**Comment by jean-emmanuel** [comment]
:dirty: means the client notifies the server when it's clean/dirty, which also means the server can safely assume it's clean unless told otherwise. The server may want to warn the user when stopping an application in an unknown state. :dirty: is added here because it's makes the apps state unnambiguous.

**Comment by Houston4444** [comment]
So what you say is, the server should consider no state as clean when the program is dirty capable.
I'll see that later, but it seems to be coherent.

**Comment by jean-emmanuel** [comment]
Well I'm not 100% sure what the server should do (no :dirty: capability means unknown state, so we're in a grey area here), but it seemed reasonable to handle is case like this in loop192.

**Comment by Houston4444** [comment]
I am not 100% sure too, that is why I said I'll see this later. In RS, I can make the loop192 template with no warning at stop, there is an option for that.
