### ISSUE TITLE
Sync to midi clock

### ISSUE THREAD

**Issue by friedolino78** [jean-emmanuel/loop192#4]
It would be great to be able to sync loop192 with a hardware looper (like ditto x4), both as master or slave.
Master mode for use with only a second looper and slave mode for use with a common clock master (like beatbuddy).

**Comment by jean-emmanuel** [comment]
It's unlikely to happen as well for the same reason as mentioned in the other issue. I made this software with osc controls only in mind, the transport part is extremely simple, since I never work with hardware sequencers I'm not sure I could do it properly anyway. The simplest solution would be to write a 3rd party midi clock receiver that drives loop192 with osc messages.
